basePath: /
definitions:
  models.DownloadOpts:
    properties:
      cbz:
        type: string
      chapters:
        type: string
      del:
        type: string
      mangaURL:
        type: string
      mtr:
        type: boolean
      pdfall:
        type: string
      pdfch:
        type: string
      pdfvol:
        type: string
      prefTrans:
        type: string
      savePath:
        type: string
      type:
        type: string
      userHash:
        type: string
    type: object
  transport.InputLogin:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  transport.InputRegister:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  transport.TokenPair:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  transport.transort_error:
    properties:
      message:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  title: AuthService
  version: "1.0"
paths:
  /api/v1/account:
    get:
      description: Get accound by id
      operationId: get-account
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.transort_error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/transport.transort_error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.transort_error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/transport.transort_error'
      security:
      - ApiKeyAuth: []
      summary: Get Account Ingo
      tags:
      - Account
  /api/v1/manga/chapters:
    get:
      description: Get Manga Chapters
      operationId: manga-chapters
      parameters:
      - description: manga_id
        in: query
        name: manga_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.transort_error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/transport.transort_error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.transort_error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/transport.transort_error'
      security:
      - ApiKeyAuth: []
      summary: Get Manga Chapters
      tags:
      - Manga
  /api/v1/manga/download:
    get:
      description: Download Manga Chapters
      operationId: manga-download
      parameters:
      - description: manga_id
        in: query
        name: manga_id
        required: true
        type: string
      - description: download_opt
        in: body
        name: downloadOps
        required: true
        schema:
          $ref: '#/definitions/models.DownloadOpts'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.transort_error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/transport.transort_error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.transort_error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/transport.transort_error'
      security:
      - ApiKeyAuth: []
      summary: Download Manga
      tags:
      - Manga
  /api/v1/manga/list:
    get:
      description: Get Manga List
      operationId: manga
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.transort_error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/transport.transort_error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.transort_error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/transport.transort_error'
      security:
      - ApiKeyAuth: []
      summary: Get Manga List
      tags:
      - Manga
  /auth/login:
    post:
      description: Generate tokens
      operationId: login
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/transport.InputLogin'
      - description: Ip
        in: header
        name: Ip
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.transort_error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/transport.transort_error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.transort_error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/transport.transort_error'
      summary: Login
      tags:
      - Auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Refresh
      operationId: refresh
      parameters:
      - description: Ip
        in: header
        name: Ip
        required: true
        type: string
      - description: tokens
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/transport.TokenPair'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.transort_error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/transport.transort_error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.transort_error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/transport.transort_error'
      summary: Refresh
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: create account
      operationId: create-account
      parameters:
      - description: Ip
        in: header
        name: Ip
        required: true
        type: string
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/transport.InputRegister'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.transort_error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/transport.transort_error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.transort_error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/transport.transort_error'
      summary: Register
      tags:
      - Auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
